
// Generated by https://quicktype.io

export interface Header {
    periodo:   string;
    ori_des:   string;
    ruta:      string;
    modalidad: string;
}

export interface BodyRolV5_2 {
    servicio:     string;
    economico:    string;
    sistema:      string;
    credenciales: Credenciales;
    descansos:    Descansos;
    lun_vie:      LunVie;
    sab:          Sab;
    dom:          Dom;
}

interface Credenciales {
    turno1cred: number;
    turno2cred: number;
    turno3cred: number;
}

interface Descansos {
    martes:    string;
    miercoles: string;
}

export interface LunVie {
    hrInicio1:  string;
    hrInicioCC: string;
    lugInicio1: string;
    hrTermino1: string;
    lugInicio2: string;
    hrInicio2:  string;
    hrTermino2: string;
    lugInicio3: string;
    hrInicio3:  string;
    hrTerCC:    string;
    lugTerCC:   string;
    hrTerMod:   string;
    hrTerT:     string;
}

export interface Sab {
    s_hrInicio1:  string;
    s_hrInicioCC: string;
    s_lugInicio1: string;
    s_hrTermino1: string;
    s_lugInicio2: string;
    s_hrInicio2:  string;
    s_hrTermino2: string;
    s_lugInicio3: string;
    s_hrInicio3:  string;
    s_hrTerCC:    string;
    s_lugTerCC:   string;
    s_hrTerMod:   string;
    s_hrTerT:     string;
}

export interface Dom {
    d_hrInicio1:  string;
    d_hrInicioCC: string;
    d_lugInicio1: string;
    d_hrTermino1: string;
    d_lugInicio2: string;
    d_hrInicio2:  string;
    d_hrTermino2: string;
    d_lugInicio3: string;
    d_hrInicio3:  string;
    d_hrTerCC:    string;
    d_lugTerCC:   string;
    d_hrTerMod:   string;
    d_hrTerT:     string;
}
