
// Generated by https://quicktype.io

//^ ---------------- ExcelRows y RegistroRol -----------------------

export interface ExcelRows {
    servicio:     string;
    economico?:    string;
    credenciales: Credenciales;
    sistema:      Sistema;
    descansos:    Descansos;
    turno1:       Turno1;
    turno2?:       Turno2;
    turno3?:       Turno3;
    termino:      Termino;
}

//^ ---------------- Cubredescansos (puede no haber) -----------------------

export interface CubreDescanso {
    servicio?:        string;
    economico?:       string;
    credenciales?:    Credenciales;
    cubrirServicios?: Descansos;
}



//^ ---------------- Intefaces Aux -----------------------

interface Credenciales {
    turno1cred:  string;
    turno2cred?: string;
    turno3cred?: string;
}

interface Descansos {
    lunes?:     string;
    martes?:    string;
    miercoles?: string;
    jueves?:    string;
    viernes?:   string;
    sabado?:    string;
    domingo?:   string;
}

enum Sistema {
    ES = "E/S",
    TF = "T/F",
}


interface Turno1 {
    cred1:        string;
    hrInicio1?:    string;
    hrInicioCC?:    string;
    lugInicio1?:   string;
    hrTermino1?:    string;
    lugTermino1?:   string;
    s_hrInicio1?:    string;
    s_hrInicioCC?:    string;
    s_lugInicio1?:   string;
    s_hrTermino1?:    string;
    s_lugTermino1?:   string;
    d_hrInicio1?:    string;
    d_hrInicioCC?:    string;
    d_lugInicio1?:   string;
    d_hrTermino1?:    string;
    d_lugTermino1?:   string;  
}

interface Turno2 {
    cred1?:        string;
    hrInicio2?:    string;
    lugInicio2?:   string;
    hrTermino2?:    string;
    lugTermino2?:   string;
    s_hrInicio2?:    string;
    s_lugInicio2?:   string;
    s_hrTermino2?:    string;
    s_lugTermino2?:   string;
    d_hrInicio2?:    string;
    d_lugInicio2?:   string;
    d_hrTermino2?:    string;
    d_lugTermino2?:   string; 
}

interface Turno3 {
    cred3?:        string;
    lugInicio3?:   string;
    hrInicio3?:    string;
    s_lugInicio3?: string;
    s_hrInicio3?:  string;
    d_lugInicio3?: string;
    d_hrInicio3?:  string;
}

interface Termino {
    hrTerCC?:    string;
    lugTerCC?:    string;
    hrTerMod?:    string;
    hrTerT?:    string;
    s_hrTerCC?:    string;
    s_lugTerCC?:    string;
    s_hrTerMod?:    string;
    s_hrTerT?:    string;
    d_hrTerCC?:    string;
    d_lugTerCC?:    string;
    d_hrTerMod?:    string;
    d_hrTerT?:    string;
}

