
// Generated by https://quicktype.io

export interface CumplimientoXeco {
    cumplimiento:     Cumplimiento;
    cumplimientoDesc: CumplimientoDescMain;
}

export interface Cumplimiento {
    porcentaje: number;
    cumplidos:  number;
}

export interface CumplimientoDescMain {
    rolPlaneado:      RolPlaneado;
    cumplimiento:     { [K in keyof CumplimientoDescDetalle]: number };
    cumplimientoDesc: CumplimientoDescDetalle;
}

export interface CumplimientoDescDetalle {
    ruta:          Array<string[] | string>;
    servicio_tipo: Array<string[] | string>;
    cred1:         Array<number[] | number>;
    cred2:         Array<number[] | number>;
    cred3:         Array<number[] | number>;
    hrInicioT1:    Array<PurpleHrInicioT | string>;
    lugIniT1:      string[];
    hrTerT1:       string[];
    lugTerT1:      string[];
    hrInicioT2:    Array<PurpleHrInicioT | string>;
    lugIniT2:      string[];
    hrTerT2:       string[];
    lugTerT2:      string[];
    hrInicioT3:    Array<PurpleHrInicioT | string>;
    lugIniT3:      string[];
    hrTerT3:       string[];
    lugTerT3:      string[];
}

export interface PurpleHrInicioT {
    limInf: number;
}

export interface RolPlaneado {
    modulo:          string;
    fechaIni:        string;
    fechaFin:        string;
    fechaConsultada: string;
    eco:             number;
}
