export const primeConfLanguaje = {
    // Obtenidas de: https://primereact.org/locale/ & https://github.com/primefaces/primelocale
    firstDayOfWeek: 1,
    dayNames: ['domingo', 'lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado'],
    dayNamesShort: ['dom', 'lun', 'mar', 'mié', 'jue', 'vie', 'sáb'],
    dayNamesMin: ['D', 'L', 'M', 'X', 'J', 'V', 'S'],
    monthNames: ['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre'],
    monthNamesShort: ['ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'nov', 'dic'],
    today: 'Hoy',
    clear: 'Limpiar',
    startsWith:	  'Comienza con',   // 'Starts with', 
    contains:	    'Contiene',   // 'Contains', 
    notContains:	'No contiene',  // 'Not contains', 
    endsWith:	    'Termina con',  // 'Ends with', 
    equals:	      'Igual a',  // 'Equals', 
    notEquals:	  'No igual a',   // 'Not equals', 
    noFilter:	    'Sin filtro',   // 'No Filter', 
    filter:	      'Filtro',   // 'Filter // only available for PrimeReact', 
    lt:	          'Menor que',   // 'Less than', 
    lte:	        'Menor o igual a',   // 'Less than or equal to', 
    gt:	          'Mayor que',   // 'Greater than', 
    gte:	        'Mayor o igual a',   // 'Greater than or equal to', 
    dateIs:	      'Fecha es',   // 'Date is', 
    dateIsNot:	  'Fecha no es',   // 'Date is not', 
    dateBefore:	  'Fecha antes de',   // 'Date is before', 
    dateAfter:	  'Fecha después de',   // 'Date is after', 
    custom:	      'Personalizado',   // 'Custom // only available for PrimeReact', 
    clear:	      'Limpiar',   // 'Clear', 
    apply:	      'Aplicar',   // 'Apply', 
    matchAll:	    'Coincidir Todos',   // 'Match All', 
    matchAny:	    'Coincidir Cualquier',   // 'Match Any', 
    addRule:	    'Agregar Regla',   // 'Add Rule', 
    removeRule:	  'Eliminar Regla',   // 'Remove Rule', 
    accept:	      'Aceptar',   // 'Yes', 
    reject:	      'Rechazar',   // 'No', 
    choose:	      'Selecciona',   // 'Choose', 
    upload:	      'Subir',   // 'Upload', 
    cancel:	      'Cancelar',   // 'Cancel', 
    completed:	  'Completado',   // 'Completed', 
    pending:	    'Pendiente',   // 'Pending', 
    //...
}