
// Generated by https://quicktype.io

export interface BodyRolV5 {
    credenciales: Credenciales;
    descansos:    Descansos;
    economico: number;
    servicio:     number | string;
    sistema:      'E/S' | 'T/F';
    lun_vie?:     LunVie;
    sab?:         Sabado;
    dom?:         Domingo;
}

export interface Credenciales {
    turno1cred:  number;
    turno3cred?: number;
    turno2cred?: number;
}

export interface Descansos {
    sabado?:    string;
    domingo?:   string;
    lunes?:     string;
    jueves?:    string;
    viernes?:   string;
    martes?:    string;
    miercoles?: string;
}

export interface LunVie {
    hrInicio1:  string;
    hrInicioCC: string;
    lugInicio1: string;
    hrTermino1: string;
    lugInicio2: string;
    hrInicio2:  string;
    hrTermino2: string;
    hrTerCC:    string;
    lugTerCC:   string;
    hrTerMod:   string;
    hrTerT:   string;
    lugInicio3?: string;
    hrInicio3?:  string;
}

export interface Sabado {
    s_hrInicio1:  string;
    s_hrInicioCC: string;
    s_lugInicio1: string;
    s_hrTermino1: string;
    s_lugInicio2: string;
    s_hrInicio2:  string;
    s_lugInicio3: string;
    s_hrInicio3:  string;
    s_hrTermino2: string;
    s_hrTerCC:    string;
    s_lugTerCC:   string;
    s_hrTerMod:   string;
    s_hrTerT:     string;
}

export interface Domingo {
    d_hrInicio1:  string;
    d_hrInicioCC: string;
    d_lugInicio1: string;
    d_hrTermino1: string;
    d_lugInicio2: string;
    d_hrInicio2:  string;
    d_lugInicio3: string;
    d_hrInicio3:  string;
    d_hrTermino2: string;
    d_hrTerCC:    string;
    d_lugTerCC:   string;
    d_hrTerMod:   string;
    d_hrTerT:     string;
}


/*

Objeto ocupado antes

const ter1 = (reg.turno2?.lugInicio2 == 'Discontinuo') ? 'Mod': null ;
    
            const data2send = {
                "validez_fechaIni": fechas[0],
                "validez_fechaFin": fechas[1],

                "idServicio": reg.servicio,
                "economico": reg.economico,
                "ruta": header[1][1],
                "servicioTipo": header[1][3],
                // "modulo": `0${moduloClave}`,
                "modulo": `0${mod}`,
                "primerTurnoCredencial": reg.credenciales.turno1cred,
                "segundoTurnoCredencial": reg.credenciales.turno2cred ?? null,
                "tercerTurnoCredencial": reg.credenciales.turno3cred ?? null,
                "sistema": reg.sistema,
                "primerDescanso": Object.keys(reg.descansos)[0] ?? null,
                "segundoDescanso": Object.keys(reg.descansos)[1] ?? null,
    
                "inicioPrimerTurno":          reg.turno1.hrInicio1,
                "salidaModulo":               sumarMinutos(reg.turno1.hrInicio1!) ,
                "inicioCierreCircuito":       reg.turno1.hrInicioCC,
                "lugarInicioServicio":        reg.turno1.lugInicio1,
                "horaTerminoLabores":         reg.turno1.hrTermino1,            
                "lugarTerminoLabores":        (ter1 || reg.turno2?.lugInicio2 || reg.termino.lugTerCC) ?? null,
    
                "inicioLaboresSegundoTurno":  reg.turno2?.hrInicio2 ?? null,
                "lugarInicioSegundo":         reg.turno2?.lugInicio2 ?? null,
                "horaTerminoSegundo":         reg.turno2?.hrTermino2 ?? null,   
                "lugarTerminoSegundo":        (reg.turno3?.lugInicio3 || reg.termino.lugTerCC) ?? null,
    
                "inicioLaboresTercerTurno":   reg.turno3?.hrInicio3 ?? null,
                "lugarInicioTercerTurno":     reg.turno3?.lugInicio3 ?? null,
                "horaTerminoTercero":         (!!reg.turno3?.hrInicio3) ? reg.termino.hrTerT : null,
                "lugarTerminoTercero":        (!!reg.turno3?.hrInicio3) ? reg.termino.lugTerCC : "null",    //! No puede ser Null Sequelize 
                "terminoModulo":              reg.termino.hrTerMod,
    
                "s_inicioPrimerTurno":          reg.turno1.s_hrInicio1,
                "s_salidaModulo":               sumarMinutos(reg.turno1.s_hrInicio1!) ,
                "s_inicioCierreCircuito":       reg.turno1.s_hrInicioCC,
                "s_lugarInicioServicio":        reg.turno1.s_lugInicio1,
                "s_horaTerminoLabores":         reg.turno1.s_hrTermino1,            
                "s_lugarTerminoLabores":        (reg.turno2?.s_lugInicio2 || reg.termino.s_lugTerCC) ?? null,
                "s_inicioLaboresSegundoTurno":  reg.turno2?.s_hrInicio2 ?? null,
                "s_lugarInicioSegundo":         reg.turno2?.s_lugInicio2 ?? null,
                "s_horaTerminoSegundo":         reg.turno2?.s_hrTermino2 ?? null,   
                "s_lugarTerminoSegundo":        (reg.turno3?.s_lugInicio3 || reg.termino.s_lugTerCC) ?? null,
                "s_inicioLaboresTercerTurno":   reg.turno3?.s_hrInicio3 ?? null,
                "s_lugarInicioTercerTurno":     reg.turno3?.s_lugInicio3 ?? null,
                "s_horaTerminoTercero":         (!!reg.turno3?.s_hrInicio3) ? reg.termino.s_hrTerT : null,
                "s_lugarTerminoTercero":        (!!reg.turno3?.s_hrInicio3) ? reg.termino.s_lugTerCC : "null",    //! No puede ser Null Sequelize 
                "s_terminoModulo":              reg.termino.s_hrTerMod,
    
                "d_inicioPrimerTurno":          reg.turno1.d_hrInicio1,
                "d_salidaModulo":               sumarMinutos(reg.turno1.d_hrInicio1!) ,
                "d_inicioCierreCircuito":       reg.turno1.d_hrInicioCC,
                "d_lugarInicioServicio":        reg.turno1.d_lugInicio1,
                "d_horaTerminoLabores":         reg.turno1.d_hrTermino1,            
                "d_lugarTerminoLabores":        (reg.turno2?.d_lugInicio2 || reg.termino.d_lugTerCC) ?? null,
                "d_inicioLaboresSegundoTurno":  reg.turno2?.d_hrInicio2 ?? null,
                "d_lugarInicioSegundo":         reg.turno2?.d_lugInicio2 ?? null,
                "d_horaTerminoSegundo":         reg.turno2?.d_hrTermino2 ?? null,   
                "d_lugarTerminoSegundo":        (reg.turno3?.d_lugInicio3 || reg.termino.d_lugTerCC) ?? null,
                "d_inicioLaboresTercerTurno":   reg.turno3?.d_hrInicio3 ?? null,
                "d_lugarInicioTercerTurno":     reg.turno3?.d_lugInicio3 ?? null,
                "d_horaTerminoTercero":         (!!reg.turno3?.d_hrInicio3) ? reg.termino.d_hrTerT : null,
                "d_lugarTerminoTercero":        (!!reg.turno3?.d_hrInicio3) ? reg.termino.d_lugTerCC : "null",    //! No puede ser Null Sequelize 
                "d_terminoModulo":              reg.termino.d_hrTerMod,
            }

 */